language: go
go:
- 1.7
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - curl
before_install:
- curl -V
- openssl aes-256-cbc -K $encrypted_f78647d3d495_key -iv $encrypted_f78647d3d495_iv
  -in onesie.json.enc -out onesie.json -d
- curl -svLO https://releases.hashicorp.com/packer/1.0.0/packer_1.0.0_linux_amd64.zip
- unzip packer_1.0.0_linux_amd64.zip
install:
- ls -al
- echo $TRAVIS_COMMIT > version.txt
script:
- "make"
- "./packer validate packer.json"
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
    repo: "icco/onesie"
