language: go
sudo: true
before_install:
- wget https://releases.hashicorp.com/packer/0.12.0/packer_0.12.0_linux_amd64.zip
- unzip packer_0.12.0_linux_amd64.zip
install:
- ls -al
script:
- ./packer validate packer.json
