language: go
sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_f78647d3d495_key -iv $encrypted_f78647d3d495_iv
  -in onesie.json.enc -out onesie.json -d
- wget https://releases.hashicorp.com/packer/0.12.0/packer_0.12.0_linux_amd64.zip
- unzip packer_0.12.0_linux_amd64.zip
install:
- ls -al
script:
- "./packer validate packer.json"
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
