---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
  - shell: echo "hello world"

  - name: Update repositories cache and install "varnish" package
    apt:
      name: varnish

  - name: Update repositories cache and install "nginx" package
    apt:
      name: nginx

  - name: Update repositories cache and install "hitch" package
    apt:
      name: hitch

  - name: Install base nginx config
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: Install application nginx config
    template: src=templates/nginx_site.conf.j2 dest=/etc/nginx/sites-available/onesie.conf force=true
    notify: restart nginx

  - name: Enable application nginx site
    file: src=/etc/nginx/sites-available/onesie.conf dest=/etc/nginx/sites-enabled/onesie.conf state=link
    notify: restart nginx

  - name: Remove default nginx site
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify: restart nginx

  - name: install varnish vcl
    template: src=templates/varnish.vcl.j2 dest=/etc/varnish/onesie.vcl mode=0644
    notify: restart varnish

  - name: install varnish config
    template: src=templates/varnish.conf.j2 dest=/etc/systemd/system/varnish.service mode=0644
    notify: restart varnish

  - shell: systemctl daemon-reload
    notify: restart varnish

  - name: Ensure nginx started
    service:
      name: nginx
      state: started

  - name: Ensure varnish started
    service:
      name: varnish
      state: started

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
  - name: restart varnish
    service:
      name: varnish
      state: restarted
