---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
  - name: "Create /opt"
    file:
      path: /opt
      state: directory
      mode: 0777
  - name: "Create /opt"
    file:
      path: /opt/onesie-configs
      state: directory
      mode: 0755

  - name: Setup www-data group
    group: name=www-data state=present

  - name: Setup www-data user
    user: name=www-data group=www-data state=present

  - name: Install gcsfuse
    template: src=templates/gcsfuse.list dest=/etc/apt/sources.list.d/gcsfuse.list

  - apt:
      name: gcsfuse
      update_cache: yes
      install_recommends: yes
  - apt:
      name: varnish
      install_recommends: yes

  - name: Setup varnish group
    group: name=varnish state=present

  - name: Setup varnish user
    user: name=varnish groups=www-data,varnish state=present append=yes

  - name: Setup varnishlog user
    user: name=varnishlog group=varnish state=present append=yes

  - apt:
      name: nginx
  - apt:
      name: git
  - apt:
      name: python-docutils
  - apt:
      name: libev-dev
  - apt:
      name: libssl-dev
  - apt:
      name: automake
  - apt:
      name: flex
  - apt:
      name: bison
  - apt:
      name: pkg-config
  - apt:
      name: fail2ban
  - apt:
      name: logrotate
  - apt:
      name: hitch
      update_cache: yes
      install_recommends: yes

  - name: Clone dehydrated
    git:
      repo: https://github.com/lukas2511/dehydrated.git
      dest: /opt/dehydrated

  - name: Configure gcsfuse
    shell: "sudo gcsfuse -o allow_other --uid=$(id -u www-data) --gid=$(id -g www-data) onesie-configs /opt/onesie-configs/"

  - name: Install dehydrated config
    template: src=templates/dehydrated.conf.j2 dest=/opt/onesie-configs/dehydrated.conf force=true

  - name: Install dehydrated hook
    template: src=templates/hook.sh dest=/opt/hook.sh force=true mode=0777

  - name: Install pem generator
    template: src=templates/pem.sh dest=/opt/pem.sh force=true mode=0777

  - name: Install base nginx config
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx

  - name: Install application nginx config
    template: src=templates/nginx_site.conf.j2 dest=/etc/nginx/sites-available/onesie.conf force=true
    notify: restart nginx

  - name: Enable application nginx site
    file: src=/etc/nginx/sites-available/onesie.conf dest=/etc/nginx/sites-enabled/onesie.conf state=link
    notify: restart nginx

  - name: Remove default nginx site
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify: restart nginx

  - name: install varnish vcl
    template: src=templates/varnish.vcl.j2 dest=/etc/varnish/onesie.vcl mode=0644
    notify: restart varnish

  - name: install varnish config
    template: src=templates/varnish.conf.j2 dest=/etc/systemd/system/varnish.service mode=0644
    notify: restart varnish

  - name: install status-server service
    template: src=templates/status-server.service dest=/etc/systemd/system/status-server.service mode=0644
    notify: restart varnish

  - name: link hitch config
    file:
      src: /opt/onesie-configs/hitch.conf
      dest: /etc/hitch/hitch.conf
      owner: root
      group: root
      state: link

  - name: Ensure status server started
    service:
      name: status-server
      state: started

  - shell: systemctl daemon-reload
    notify: restart varnish

  - name: Ensure nginx started
    service:
      name: nginx
      state: started

  - name: Ensure varnish started
    service:
      name: varnish
      state: started

  - name: install update cron
    cron:
      name: "pull updates off of sub"
      job: "/opt/wrkr >> /var/log/wrkr.log 2>&1"

  - name: install dehydrated cron
    cron:
      name: "dehydrated cron"
      job: "/opt/dehydrated/dehydrated -c --config /opt/onesie-configs/dehydrated.conf >> /var/log/dehydrated.log 2>&1"
      minute: "*/10"

  - name: install another cron
    cron:
      name: "pem generator"
      job: "/opt/pem.sh >> /var/log/pem.log 2>&1"
      minute: "*/12"

  - name: Copy stackdriver script
    template: src=templates/stackdriver.sh dest=/opt/onesie-configs/install-stackdriver.sh mode=0755

  - name: Install stackdriver monitoring
    shell: bash /opt/onesie-configs/install-stackdriver.sh

  - name: fix varnish perms
    file: dest=/var/lib/varnish owner=varnish group=varnish recurse=yes

  - name: validate varnish
    shell: sudo /usr/sbin/varnishd -C -f /etc/varnish/onesie.vcl

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
  - name: restart varnish
    service:
      name: varnish
      state: restarted
